#!/usr/bin/env python3
"""
Add Missing Entities Script

This script automatically adds all missing entities to missing_fields.json
with the required fields_obj_transform field.
"""

import json
from pathlib import Path

def main():
    """Add missing entities to missing_fields.json."""
    
    # Load existing missing_fields.json
    missing_fields_file = "missing_fields.json"
    with open(missing_fields_file, 'r') as f:
        missing_fields_data = json.load(f)
    
    # List of missing entities from the find_missing_entities.py output
    missing_entities = [
        "flu_fl_baker_unincorporated",
        "flu_fl_bay_unified",
        "flu_fl_brevard_melbourne",
        "flu_fl_calhoun_unincorporated",
        "flu_fl_duval_jacksonville",
        "flu_fl_gadsden_unincorporated",
        "flu_fl_gulf_unincorporated",
        "flu_fl_hardee_bowling_green",
        "flu_fl_hardee_wauchula",
        "flu_fl_hardee_zolfo_springs",
        "flu_fl_hendry_unincorporated",
        "flu_fl_highlands_avon_park",
        "flu_fl_indian_river_unincorporated",
        "flu_fl_jackson_unincorporated",
        "flu_fl_jefferson_unincorporated",
        "flu_fl_lake_astatula",
        "flu_fl_lake_clermont",
        "flu_fl_lake_eustis",
        "flu_fl_lake_fruitland_park",
        "flu_fl_lake_mascotte",
        "flu_fl_lee_fort_myers",
        "flu_fl_leon_unified",
        "flu_fl_liberty_unincorporated",
        "flu_fl_miami-dade_incorporated",
        "flu_fl_miami-dade_unincorporated",
        "flu_fl_nassau_unincorporated",
        "flu_fl_palm_beach_west_palm_beach",
        "flu_fl_pinellas_unified",
        "flu_fl_polk_unincorporated",
        "flu_fl_putnam_unincorporated",
        "flu_fl_st_lucie_port_st_lucie",
        "flu_fl_taylor_unincorporated",
        "flu_fl_washington_unincorporated",
        "parcel_geo_al_autauga",
        "parcel_geo_al_baldwin",
        "parcel_geo_al_barbour",
        "parcel_geo_al_bibb",
        "parcel_geo_al_blount",
        "parcel_geo_al_bullock",
        "parcel_geo_al_butler",
        "parcel_geo_al_calhoun",
        "parcel_geo_al_chambers",
        "parcel_geo_al_cherokee",
        "parcel_geo_al_chilton",
        "parcel_geo_al_choctaw",
        "parcel_geo_al_clarke",
        "parcel_geo_al_clay",
        "parcel_geo_al_cleburne",
        "parcel_geo_al_coffee",
        "parcel_geo_al_colbert",
        "parcel_geo_al_conecuh",
        "parcel_geo_al_coosa",
        "parcel_geo_al_covington",
        "parcel_geo_al_crenshaw",
        "parcel_geo_al_cullman",
        "parcel_geo_al_dale",
        "parcel_geo_al_dallas",
        "parcel_geo_al_dekalb",
        "parcel_geo_al_elmore",
        "parcel_geo_al_escambia",
        "parcel_geo_al_etowah",
        "parcel_geo_al_fayette",
        "parcel_geo_al_franklin",
        "parcel_geo_al_geneva",
        "parcel_geo_al_greene",
        "parcel_geo_al_hale",
        "parcel_geo_al_henry",
        "parcel_geo_al_houston",
        "parcel_geo_al_jackson",
        "parcel_geo_al_jefferson",
        "parcel_geo_al_lamar",
        "parcel_geo_al_lauderdale",
        "parcel_geo_al_lawrence",
        "parcel_geo_al_lee",
        "parcel_geo_al_limestone",
        "parcel_geo_al_lowndes",
        "parcel_geo_al_macon",
        "parcel_geo_al_madison",
        "parcel_geo_al_marengo",
        "parcel_geo_al_marion",
        "parcel_geo_al_marshall",
        "parcel_geo_al_mobile",
        "parcel_geo_al_monroe",
        "parcel_geo_al_montgomery",
        "parcel_geo_al_morgan",
        "parcel_geo_al_perry",
        "parcel_geo_al_pickens",
        "parcel_geo_al_pike",
        "parcel_geo_al_randolph",
        "parcel_geo_al_russell",
        "parcel_geo_al_shelby",
        "parcel_geo_al_st_clair",
        "parcel_geo_al_sumter",
        "parcel_geo_al_talladega",
        "parcel_geo_al_tallapoosa",
        "parcel_geo_al_tuscaloosa",
        "parcel_geo_al_walker",
        "parcel_geo_al_washington",
        "parcel_geo_al_wilcox",
        "parcel_geo_al_winston",
        "parcel_geo_de_sussex",
        "parcel_geo_fl_baker",
        "parcel_geo_fl_bradford",
        "parcel_geo_fl_calhoun",
        "parcel_geo_fl_columbia",
        "parcel_geo_fl_dixie",
        "parcel_geo_fl_escambia",
        "parcel_geo_fl_franklin",
        "parcel_geo_fl_gadsden",
        "parcel_geo_fl_gilchrist",
        "parcel_geo_fl_glades",
        "parcel_geo_fl_gulf",
        "parcel_geo_fl_hamilton",
        "parcel_geo_fl_hardee",
        "parcel_geo_fl_hendry",
        "parcel_geo_fl_hendry2",
        "parcel_geo_fl_hernando",
        "parcel_geo_fl_hillsborough",
        "parcel_geo_fl_holmes",
        "parcel_geo_fl_jackson",
        "parcel_geo_fl_jefferson",
        "parcel_geo_fl_lafayette",
        "parcel_geo_fl_levy",
        "parcel_geo_fl_liberty",
        "parcel_geo_fl_madison",
        "parcel_geo_fl_manatee",
        "parcel_geo_fl_marion",
        "parcel_geo_fl_marion2",
        "parcel_geo_fl_miami-dade",
        "parcel_geo_fl_monroe",
        "parcel_geo_fl_nassau",
        "parcel_geo_fl_okeechobee",
        "parcel_geo_fl_putnam",
        "parcel_geo_fl_sumter3",
        "parcel_geo_fl_suwannee",
        "parcel_geo_fl_taylor",
        "parcel_geo_fl_union",
        "parcel_geo_fl_wakulla",
        "parcel_geo_fl_washington",
        "parcel_geo_ga_appling",
        "parcel_geo_ga_atkinson",
        "parcel_geo_ga_atkinson_x",
        "parcel_geo_ga_bacon",
        "parcel_geo_ga_baker",
        "parcel_geo_ga_baldwin",
        "parcel_geo_ga_baldwin_x",
        "parcel_geo_ga_banks",
        "parcel_geo_ga_banks_x",
        "parcel_geo_ga_barrow",
        "parcel_geo_ga_bartow",
        "parcel_geo_ga_berrien",
        "parcel_geo_ga_bibb",
        "parcel_geo_ga_bleckley",
        "parcel_geo_ga_bleckley_x",
        "parcel_geo_ga_brantley",
        "parcel_geo_ga_brooks",
        "parcel_geo_ga_brooks_x",
        "parcel_geo_ga_bryan",
        "parcel_geo_ga_bryan_x",
        "parcel_geo_ga_bulloch",
        "parcel_geo_ga_burke",
        "parcel_geo_ga_burke_x",
        "parcel_geo_ga_butts",
        "parcel_geo_ga_calhoun",
        "parcel_geo_ga_camden",
        "parcel_geo_ga_candler",
        "parcel_geo_ga_candler_x",
        "parcel_geo_ga_carroll",
        "parcel_geo_ga_carroll_x",
        "parcel_geo_ga_catoosa",
        "parcel_geo_ga_charlton",
        "parcel_geo_ga_chatham",
        "parcel_geo_ga_chattahoochee",
        "parcel_geo_ga_chattooga",
        "parcel_geo_ga_cherokee",
        "parcel_geo_ga_clarke",
        "parcel_geo_ga_clay",
        "parcel_geo_ga_clay_x",
        "parcel_geo_ga_clayton",
        "parcel_geo_ga_clayton_x",
        "parcel_geo_ga_clinch",
        "parcel_geo_ga_clinch_x",
        "parcel_geo_ga_cobb",
        "parcel_geo_ga_colquitt",
        "parcel_geo_ga_columbia",
        "parcel_geo_ga_coweta",
        "parcel_geo_ga_crawford",
        "parcel_geo_ga_crisp",
        "parcel_geo_ga_dade",
        "parcel_geo_ga_dawson",
        "parcel_geo_ga_decatur",
        "parcel_geo_ga_dekalb",
        "parcel_geo_ga_dodge",
        "parcel_geo_ga_dooly",
        "parcel_geo_ga_dougherty",
        "parcel_geo_ga_douglas",
        "parcel_geo_ga_early",
        "parcel_geo_ga_echols",
        "parcel_geo_ga_effingham",
        "parcel_geo_ga_elbert",
        "parcel_geo_ga_emanuel",
        "parcel_geo_ga_evans",
        "parcel_geo_ga_fannin",
        "parcel_geo_ga_fayette",
        "parcel_geo_ga_floyd",
        "parcel_geo_ga_forsyth",
        "parcel_geo_ga_franklin",
        "parcel_geo_ga_fulton",
        "parcel_geo_ga_gilmer",
        "parcel_geo_ga_glascock",
        "parcel_geo_ga_glynn",
        "parcel_geo_ga_gordon",
        "parcel_geo_ga_grady",
        "parcel_geo_ga_greene",
        "parcel_geo_ga_gwinnett",
        "parcel_geo_ga_habersham",
        "parcel_geo_ga_hall",
        "parcel_geo_ga_hancock",
        "parcel_geo_ga_haralson",
        "parcel_geo_ga_harris",
        "parcel_geo_ga_hart",
        "parcel_geo_ga_heard",
        "parcel_geo_ga_henry",
        "parcel_geo_ga_houston",
        "parcel_geo_ga_jackson",
        "parcel_geo_ga_jasper",
        "parcel_geo_ga_jeffdavis",
        "parcel_geo_ga_jefferson",
        "parcel_geo_ga_jenkins",
        "parcel_geo_ga_johnson",
        "parcel_geo_ga_jones",
        "parcel_geo_ga_lamar",
        "parcel_geo_ga_lanier",
        "parcel_geo_ga_laurens",
        "parcel_geo_ga_lee",
        "parcel_geo_ga_liberty",
        "parcel_geo_ga_lincoln",
        "parcel_geo_ga_long",
        "parcel_geo_ga_lumpkin",
        "parcel_geo_ga_macon",
        "parcel_geo_ga_madison",
        "parcel_geo_ga_marion",
        "parcel_geo_ga_mcduffie",
        "parcel_geo_ga_mcintosh",
        "parcel_geo_ga_meriwether",
        "parcel_geo_ga_miller",
        "parcel_geo_ga_mitchell",
        "parcel_geo_ga_monroe",
        "parcel_geo_ga_montgomery",
        "parcel_geo_ga_morgan",
        "parcel_geo_ga_murray",
        "parcel_geo_ga_muscogee",
        "parcel_geo_ga_newton",
        "parcel_geo_ga_oconee",
        "parcel_geo_ga_oglethorpe",
        "parcel_geo_ga_paulding",
        "parcel_geo_ga_peach",
        "parcel_geo_ga_pickens",
        "parcel_geo_ga_pierce",
        "parcel_geo_ga_pike",
        "parcel_geo_ga_polk",
        "parcel_geo_ga_pulaski",
        "parcel_geo_ga_putnam",
        "parcel_geo_ga_quitman",
        "parcel_geo_ga_rabun",
        "parcel_geo_ga_randolph",
        "parcel_geo_ga_richmond",
        "parcel_geo_ga_rockdale",
        "parcel_geo_ga_schley",
        "parcel_geo_ga_schley_x",
        "parcel_geo_ga_screven",
        "parcel_geo_ga_seminole",
        "parcel_geo_ga_spalding",
        "parcel_geo_ga_stephens",
        "parcel_geo_ga_stewart",
        "parcel_geo_ga_sumter",
        "parcel_geo_ga_talbot",
        "parcel_geo_ga_talbot_x",
        "parcel_geo_ga_taliaferro",
        "parcel_geo_ga_tattnall",
        "parcel_geo_ga_taylor",
        "parcel_geo_ga_telfair",
        "parcel_geo_ga_terrell",
        "parcel_geo_ga_thomas",
        "parcel_geo_ga_tift",
        "parcel_geo_ga_toombs",
        "parcel_geo_ga_towns",
        "parcel_geo_ga_treutlen",
        "parcel_geo_ga_troup",
        "parcel_geo_ga_turner",
        "parcel_geo_ga_twiggs",
        "parcel_geo_ga_union",
        "parcel_geo_ga_upson",
        "parcel_geo_ga_walker",
        "parcel_geo_ga_walton",
        "parcel_geo_ga_ware",
        "parcel_geo_ga_warren",
        "parcel_geo_ga_washington",
        "parcel_geo_ga_wayne",
        "parcel_geo_ga_webster",
        "parcel_geo_ga_wheeler",
        "parcel_geo_ga_white",
        "parcel_geo_ga_whitfield",
        "parcel_geo_ga_wilcox",
        "parcel_geo_ga_wilkes",
        "parcel_geo_ga_wilkinson",
        "parcel_geo_ga_worth",
        "zoning_fl_leon_county_unified",
        "zoning_fl_miami-dade_incorporated",
        "zoning_fl_miami-dade_unincorporated",
        "zoning_fl_palm_beach_county_unified",
        "zoning_fl_pinellas_belleair",
        "zoning_fl_volusia_port_orange"
    ]
    
    # Add missing entities
    added_count = 0
    for entity in missing_entities:
        if entity not in missing_fields_data:
            missing_fields_data[entity] = {
                "fields_obj_transform": "MANUAL_REQUIRED"
            }
            added_count += 1
    
    # Save updated file
    with open(missing_fields_file, 'w') as f:
        json.dump(missing_fields_data, f, indent=2)
    
    print(f"[INFO] Added {added_count} missing entities to {missing_fields_file}")
    print(f"[INFO] Total entities in file: {len(missing_fields_data)}")

if __name__ == "__main__":
    main() 