-- for data from sales download tool on website
CREATE TABLE raw_okaloosa_sales_dwnld
(
	pin text,
    s_address text,
    sale_date date,
	sale_amt int,
    sale_qual text,
    sale_bk text,
	sale_pg text,
    acres text,
    tax_dist text,
    year_blt int,
    sqft int,
    str text,
    sale_type_alt text
);

/*
-- changed around 4/2025
CREATE TABLE raw_okaloosa_sales_dwnld
(
	pin text,
	o_name1 text,
	o_name2 text,
	o_address1 text,
	o_address2 text,
	o_address3 text,
	o_city text,
	o_state text,
	o_zipcode text,
	o_zipcode4 text,
	sale_amt int,
	sale_year int,
	sale_date date,
	sale_vac text,
	sale_typ text,
	sale_qual text,
	sale_bk text,
	sale_pg text
);
*/

CREATE TABLE parcels_template2_okaloosa
(
  s_section smallint,
  s_township text,
  s_range text,
  subdiv_id text,
  subdiv_nm text,
  subdiv_nm2 text,
  block_pin text,
  lot_pin text,
  block_legal text,
  lot_legal text,
  fips text,
  pin_geom text,
  pin text,
  pin_clean text,
  pin2 text,
  pin2_clean text,
  altkey text,
  altkey_clean text,
  upin text,
  pin_fdor text,
  acres_deed double precision,
  acres_gis double precision,
  condo text,
  condo_method text,
  condo_key text,
  name_misc text,
  owner_occupied text,
  foreign_owner text,
  o_name1 text,
  o_name2 text,
  o_name3 text,
  o_address1 text,
  o_address2 text,
  o_address3 text,
  o_city text,
  o_state text,
  o_country text,
  o_zipcode text,
  o_zipcode4 text,
  s_number text,
  s_pdir text,
  s_name text,
  s_type text,
  s_sdir text,
  s_unit text,
  s_address text,
  s_city text,
  s_state text,
  s_zipcode text,
  s_zipcode4 text,
  sale1_amt bigint,
  sale1_year smallint,
  sale1_date text,
  sale1_date_date date,
  sale1_vac text,
  sale1_typ text,
  sale1_qual text,
  sale1_multi text,
  sale1_bk text,
  sale1_pg text,
  sale1_docnum text,
  sale1_grantor text,
  sale1_grantee text,
  sale2_amt bigint,
  sale2_year smallint,
  sale2_date text,
  sale2_date_date date,
  sale2_vac text,
  sale2_typ text,
  sale2_qual text,
  sale2_multi text,
  sale2_bk text,
  sale2_pg text,
  sale2_docnum text,
  sale2_grantor text,
  sale2_grantee text,
  sale3_amt bigint,
  sale3_year smallint,
  sale3_date text,
  sale3_date_date date,
  sale3_vac text,
  sale3_typ text,
  sale3_qual text,
  sale3_multi text,
  sale3_bk text,
  sale3_pg text,
  sale3_docnum text,
  sale3_grantor text,
  sale3_grantee text,
  sale4_amt bigint,
  sale4_year smallint,
  sale4_date text,
  sale4_date_date date,
  sale4_vac text,
  sale4_typ text,
  sale4_qual text,
  sale4_multi text,
  sale4_bk text,
  sale4_pg text,
  sale4_docnum text,
  sale4_grantor text,
  sale4_grantee text,
  sale5_amt bigint,
  sale5_year smallint,
  sale5_date text,
  sale5_date_date date,
  sale5_vac text,
  sale5_typ text,
  sale5_qual text,
  sale5_multi text,
  sale5_bk text,
  sale5_pg text,
  sale5_docnum text,
  sale5_grantor text,
  sale5_grantee text,
  mrkt_bld bigint,
  mrkt_impr integer,
  mrkt_lnd bigint,
  mrkt_ag integer,
  mrkt_tot bigint,
  assd_tot bigint,
  exempt_tot bigint,
  taxable_tot bigint,
  homestead text,
  tax_amt1 numeric(10,2),
  tax_amt2 numeric(10,2),
  tax_amt3 numeric(10,2),
  num_bldg smallint,
  res_units int,
  sqft_htd integer,
  sqft_tot integer,
  sqft_adj integer,
  stories smallint,
  yrblt_act smallint,
  yrblt_eff smallint,
  num_bed smallint,
  num_bath smallint,
  num_bath_half smallint,
  luse text,
  luse_d text,
  lusedor text,
  lusedor_d text,
  zoning text,
  legal_full text,
  legal1 text,
  legal2 text,
  legal3 text,
  legal4 text,
  legal5 text,
  legal6 text,
  d_date text,
  d_county text,
  sale1q_amt integer,
  sale1q_year smallint,
  sale1q_date text,
  sale1q_date_date date
)
WITH (
  OIDS=FALSE
);
ALTER TABLE parcels_template_okaloosa
  OWNER TO postgres;